#!/bin/bash
cd $(dirname $BASH_SOURCE)


# gitconfig
ln -sf $PWD/gitconfig ~/.gitconfig


# vimrc
curl --insecure --create-dirs -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf $PWD/vimrc ~/.vimrc

mkdir -p ~/.config/nvim/autoload
ln -sf $PWD/vimrc ~/.config/nvim/init.vim
ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/

nvim --headless +PlugInstall +qall
