name: Test
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    name: 'macOS'
    runs-on: 'macos-latest'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test make install
        run: make install
      - name: Test make update
        run: make update
      - name: Test make clean
        run: make clean
